### ISSUE TITLE
popping up advertising on d2bot.exe

### ISSUE THREAD

**Issue by Fandman** [d2botsharp/d2bot#10]
Hi, when i start my Bots now there is an popup advertising that tell "You have exceeded your allotted Runs per day, purchase 100 more runs for 9,99$"

Well my Bots are still running but it makes me worry about. Do i need to ?

**Comment by ryclow604** [comment]
I thought kolbot was free? im getting the same message

**Comment by Shadowmeph** [comment]
same here whats this?

**Comment by Ownasaurus** [comment]
https://www.timeanddate.com/ :)

**Comment by ryclow604** [comment]
Time and date?

**Comment by Shadowmeph** [comment]
well I hope this is what it is the original post shows march 31 /18 so if it is you got me lol

**Comment by Ownasaurus** [comment]
Yeah that's the day before April fool's day. So it is probably due to a difference in time zone. I suspect the message will disappear tomorrow.
