### ISSUE TITLE
exceeded runs per day d2bot.exe

### ISSUE THREAD

**Issue by ryclow604** [d2botsharp/d2bot#15]
getting a pop up that wants me to buy 100 more runs, I thought kolbot was free?

**Comment by MWEDVAG** [comment]
Yesterday, I also opened a thread here for this. noah says: "This is not part of d2b, please post to the correct repo."

can you say me the right repo? the popup is very scary, i can understand that you ask..

**Comment by noah-** [comment]
Hello, thank you for participating in the April 1st festivities.

**Comment by wilkinsa** [comment]
This is golden
