### ISSUE TITLE
I can´t install d2 nor d2lod from D2-1.14b-Installer-enGB nor  from D2LOD-1.14b-Installer-enGB.

### ISSUE THREAD

**Issue by pirx-pirx** [d2botsharp/d2bot#17]

**Comment by pirx-pirx** [comment]
I have got Windows 10 and I cant run this installers. They make sound when I active the Play D2LoD but nothing happens.
I have desinstalled diablo II but cant run these installers.

**Comment by tommyonsn** [comment]
我也是，我载的亚服的-tw，同样不行。中文的d2大概早已经被暴雪放弃了。
me too...

**Comment by mf022** [comment]
maybe you should use the torrents for 1.12a or 1.14b
https://github.com/blizzhackers/diablo2-tools-utilities/tree/master/D2LoD-torrent-files
