### ISSUE TITLE
Profiles Wont Start (Status: Stopped)

### ISSUE THREAD

**Issue by ImLeg3ndLol** [d2botsharp/d2bot#19]
Running 6 Profiles without any issue, came back and all but one profile showed status "stopped" even though there game windows were open and characters were sitting in lobby. Tried closing and restarting the profiles, d2 window opens but takes no action and still shows status "stopped"

Familiar with Kolbot I just did a clean uninstall, reinstall, brand new went to run the first profile to make the char config and issue persists. Cant start D2botLead or D2botfollow profiles, any advice/suggestions are appreciated!

**Comment by noah-** [comment]
please update to latest version
