### ISSUE TITLE
Lighning sorc doesnt attack or attack in wrong direction...

### ISSUE THREAD

**Issue by pirx-pirx** [d2botsharp/d2bot#26]
Lighning sorc doesnt attack or attack in wrong direction... and she teleports passing Nihla or Shenk in 2 jumps at least.
Any help please
[info.log](https://github.com/d2botsharp/d2bot/files/7981331/info.log)
?
[info.log](https://github.com/d2botsharp/d2bot/files/7981335/info.log)

**Comment by mf022** [comment]
> ... Any help please
> [info.log](https://github.com/d2botsharp/d2bot/files/7981331/info.log)
> ?
> [info.log](https://github.com/d2botsharp/d2bot/files/7981335/info.log)

what kind of bot you are trying to use?
why your log includes **D2R** mention?
is your issue related to <https://github.com/aeon0/botty/issues/501>?

**Comment by pirx-pirx** [comment]
Sorry .. mistake
